### ISSUE TITLE
Convert tasks-report-macro to task-report and support the pages parameter

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-confluence-migrator-pro#139]
The tasks-report-macro bridge is not really necessary, we can easily convert to or task-report macro. This would also allow us to support the pages parameter.

For this task, please:
 - convert the pages parameters to proper wiki references
 -  convert the spaces parameter to proper wiki references
 - make sure to handle the status of migrated tasks well. To be checked, but AFAIK Confluence has two states for tasks: todo and done, and XWiki has three stats: todo, in progress, done.  For todo, the status should be converted to todo and not to in progress

**Comment by trrenty** [comment]
The "incomplete" status of the tasks coming from confluence is mapped to "InProgress" in XWiki. This decision was made in the early development of the task application. Not sure if changing it right now would be a good idea.
