### ISSUE TITLE
Allow to re-run macro conversions post-import

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-confluence-migrator-pro#16]
This feature can be an interesting post-import script, to be triggered manually by the administrator.

It can be helpful in case new extensions or new upgrades to existing extensions provide new support for some confluence macros that need to be converted before being usable in XWiki.

One way to implement this is to provide an extra input filter stream, based on `xwiki+instance`.

**Comment by snazare** [comment]
could be interesting to add an utility section with scripts that can be executed post import

**Comment by aubincleme** [comment]
> I'd be in favor of providing an XDOM script to rename macros in documents, and probably outside Confluence Migrator Pro (but the confluence migrator pro could depend on it and point users to it).

+1, it would be acceptable for users I think

Main challenge I see is that a user may want to run multiple scripts at once, which could be a hassle. Currently the scripts that we provide on snippets.xwiki.org are not really made to be executed in chain

**Comment by michitux** [comment]
When I mentioned this idea, my idea was that it would roughly work like this: We decide that, e.g., we don't want to provide a `confluence_children` macro anymore but instead migrate the content to use a proper XWiki document tree macro. Therefore, we start providing a macro converter that converts the Confluence children macro into a document tree macro. For existing installations, we would offer a tool that allows to run this migration on a selected space, or a whole wiki. This tool could present a list of all macro conversions we offer with checkboxes to select which ones to run. Depending on the use case, this converter for already migrated content could be slightly different. For example, it could expect both a `children` macro, that is only converted if it has parameters, and a `confluence_children` macro, that is always converted. Still, I think the converter in the migrator and the one for the existing content should share the main logic, e.g., how to transform parameters.

**Comment by snazare** [comment]
closing as inavtice as we are using the xdom script at the moment.
