### ISSUE TITLE
Convert Content formatting macros to XWiki sytax

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator-pro#161]
We have identified these [Content Formatting Macros for Confluence](https://github.com/xwikisas/application-confluence-migrator-pro/issues/161#issue-2482914008) that can be converted into XWiki syntax computed from macro content and parameters, that results in a similar behaviour. Please convert these macros into appropriate XWiki syntax upon import:

- table,
- td, 
- tr, 
- span, 
- bgcolor,
- align, 
- th, 
- auibutton, 
- div, 
- highlight, 
- center, 
- auiprogressstepstatic, 
- auiprogress, 
- auitabspage, 
- auitabs, 
- img, 
- alert, 
- button, 
- tbody, 
- pre, 
- tm, 
- lozenge, 
- reg-tm, 
- p

**Comment by trrenty** [comment]
* table - not implemented
* td - not implemented
* tr - not implemented
* span - not implemented
* bgcolor - not implemented
* align - not implemented
* th - not implemented
* auibutton - not implemented
* div - not implemented
* highlight - not implemented
* center - not implemented
* auiprogressstepstatic - not implemented
* auiprogress - not implemented
* auitabspage - not implemented
* auitabs - not implemented
* img - https://jira.xwiki.org/browse/CONFLUENCE-285
* alert - https://jira.xwiki.org/browse/CONFLUENCE-276
* button - not implemented
* tbody - not implemented
* pre - not implemented
* tm - not implemented
* lozenge - not implemented
* reg-tm - not implemented
* p - not implemented
