### ISSUE TITLE
Convert Scroll Image Map macros to XWiki syntax

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator-pro#162]
We have identified these [Scroll ImageMap for Confluence](https://help.k15t.com/scroll-imagemap/2.6/cloud/) macros that can be converted into XWiki syntax computed from macro content and parameters, that results in a similar behaviour. Please convert these macros into appropriate XWiki syntax upon import:

- scroll-imagemap, 
- imagemap, 
- map

**Comment by Farcasut** [comment]
Invalid
