### ISSUE TITLE
Convert projectdoc-definition-list-macro to XWiki syntax

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator-pro#167]
Please convert the projectdoc-definition-list-macro from the [Project Documentation Macros](https://www.smartics.eu/confluence/display/CONFMAC/Project+Documentation+Macros?pk_campaign=marketplace&pk_kwd=documentation-macros) plugin into XWiki syntax upon import, so that the result will be the content of the macro.

**Comment by Farcasut** [comment]
Not implemented.
