### ISSUE TITLE
As part of the migration report of a Confluence package, list the Confluence macros that are missing in XWiki

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-confluence-migrator-pro#32]
The goal of this improvement is to provide more visibility to administrators during the migration of their instance, with indications of which macros need to be added to XWiki after the import of a Confluence space.

**Comment by snazare** [comment]
The following macros are not available 

The following macros are available but have limitations (jira, profile-picture)

**Comment by snazare** [comment]
it may be more useful to have a global page that shows all macros used across the instance and the number of usage. to decide if we should still release the individual list per space or if we should focus on a global macro list.
