### ISSUE TITLE
Add the ability to interrupt a migration

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-confluence-migrator-pro#53]
It can be useful to kill / terminate a migration process when investigating a bug. There's currently no easy way to do it in the confluence migrator application.

It could be implemented with a "stop" button on migration pages.

Important: the temporary files created by the confluence xml package in the `work` directory should be cleaned up.

**Comment by snazare** [comment]
cancel button on Migrations livetable Actions
cancel option in Migration page, import step
