### ISSUE TITLE
Hide the "Not supported macros" section if there are none

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-confluence-migrator-pro#66]
**Small prerequisites**: along with the latest version of the extension and a trial license, it is recommended to have a migration package (with or without Confluence macros).

It was introduced in version 1.10.0 as fixed for issue #32. At the time, if you've migrated package, it doesn't matter if the supported macros are in the package or not. You get all the information without additional information - the number of macros and names.

![image](https://github.com/xwikisas/application-confluence-migrator-pro/assets/56109799/c0803438-80b1-464c-b9e4-2590d8cb8d86)

IMO, if the package doesn't contain unsupported macros, a user must not see _Not supported macros_. The result with the sentence _Supported macros_ has to print the counter or names of macros.

Additionally, if the user clicks the link to see the entire list, the documentation page will be displayed with no list.

**Comment by snazare** [comment]
to do: if the list is empty, show a message in each section saying 

"No supported macros found in this package."
"No unsupported macros found in this package."

**Comment by trrenty** [comment]
![image](https://github.com/xwikisas/application-confluence-migrator-pro/assets/45433221/0b1a1eed-75b7-4329-92af-3221517d0a5c)
