### ISSUE TITLE
Ability to reuse package analysis for several migrations

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-confluence-migrator-pro#86]
[CONFLUENCE-207](https://jira.xwiki.org/browse/CONFLUENCE-207) Allows specifying the folder in which the package is extracted and when extracted data is already there, Confluence-XML attempts to reuse this extraction, which makes it way faster.

As is it advisable to migrate from full exports (for link creation), even when migrating a few select spaces at a time, being able to skip package analysis between the spaces would make us win a lot of time.

Things to be careful about:
 - it is not supported to reuse extracted data from another version of the Confluence-XML package, and this should be detected an blocked by Confluence Migrator Pro
 - the extracted data needs to be cleaned up. If it left in the xwiki-temp "work" folder, XWiki will take a lot of time recursively removing all these files (this can take hours), making it appear stuck.

**Comment by snazare** [comment]
* cancel button on Migrations livetable Actions
* cancel option in Migration page, import step
