### ISSUE TITLE
Clicking on filtered space selection labels is buggy

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-confluence-migrator-pro#91]
Clicking on labels after searches lead to strange results: the wrong checkboxes are checked.

https://github.com/xwikisas/application-confluence-migrator-pro/assets/3817365/b814545c-6c2e-492b-9058-e2d45f10cd6e

**Comment by snazare** [comment]
Hi @raphj I do not reproduce this on Confluence Migrator Pro 1.22.0, XWiki 15.10.10. Have you seen this behaviour recently? Should I close this ticket if it doesn't reproduce?
